spring:
    profies:
        active：
        - dev
---
spring:
    profies: dev  #测试环境
    application:
        name: config-zhengl-dev
---
spring:
    profies: test #测试环境
    application:
        name: config-zhengl-test

#必须以utf-8保存
