spring:
    profiles:
        active：
        - dev
---
spring:
    profiles: dev  #测试环境
    application:
        name: config-server-zhengl-dev
---
spring:
    profiles: test #测试环境
    application:
        name: config-server-zhengl-test

#必须以utf-8保存
